services:
  db:
    image: postgres:latest
    container_name: psql_products
    restart: on-failure:5  #В случае ошибки контейнер попробует перезапуститься 5 раз
    env_file:
      - environment/.env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d  # Монтируем  папку с SQL скриптами
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  minio:
    image: minio/minio:latest
    container_name: minio
    env_file:
      - environment/.env
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"  
      - "9001:9001"  
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
      start_period: 30s


volumes:
  pg_data:
  minio_data: