version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "8091:6379"
    environment:
      - REDIS_PASSWORD=your_secure_password
    volumes:
      - redis_data:/data
    restart: unless-stopped

  app:
    build: .
    ports:
      - "8089:8080"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=your_secure_password
      - REDIS_DB=0
    depends_on:
      - redis
    restart: unless-stopped

volumes:
  redis_data: