global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'auth-service'
    static_configs:
      - targets: ['172.17.0.1:10664']
  - job_name: 'comment-service'
    static_configs:
      - targets: ['172.17.0.1:10665']
  - job_name: 'item-service'
    static_configs:
      - targets: ['172.17.0.1:10666']
  - job_name: 'ETL-service'
    static_configs:
      - targets: ['172.17.0.1:10667']

