global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 50s 

scrape_configs:
  - job_name: 'auth-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['sso:10664']
    
  - job_name: 'search-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['search_service:10667']
    
  - job_name: 'facade-app'
    metrics_path: /metrics
    static_configs:
      - targets: ['go-app:10666']

