global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'auth-service'
    static_configs:
      - targets: ['host.docker.internal:10664']
  - job_name: 'comment-service'
    static_configs:
      - targets: ['host.docker.internal:10665']
  - job_name: 'item-service'
    static_configs:
      - targets: ['host.docker.internal:10666']
  - job_name: 'ETL-service'
    static_configs:
      - targets: ['host.docker.internal:10667']

