global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'auth-service'
    static_configs:
      - targets: ['sso:10664']
  - job_name: 'comment-service'
    static_configs:
      - targets: ['host.docker.internal:10665']
  - job_name: 'item-service'
    static_configs:
      - targets: ['host.docker.internal:10666']
  - job_name: 'ETL-service'
    static_configs:
      - targets: ['manage-item-etl:10667']
  - job_name: 'item-crud-service'
    static_configs:
      - targets: ['manage-item-crud:10668']
  - job_name: 'facade-service'
    static_configs:
      - targets: ['facade-app:10671']

